language: node_js
node_js:
  - "5"

env:
  - NODE_ENV=production

before_install:
  - rvm install 2.3.1

install:
  - bundle install
  - npm install
  - npm install -g lodash marked varstream svgicons2svgfont node-gyp ttf2woff2
  - npm install -g gulp

before_script: bin/rspec

script: bundle exec middleman build --clean

branches:
  only:
  - master
